name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.devcontainer/**/*'
      - '.github/workflows/devcontainer.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v5
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: BUTR
          password: ${{ secrets.TOKEN_GPR }}
    - 
        name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/butr/bannerlord.blse-devcontainer
          cacheFrom: ghcr.io/butr/bannerlord.blse-devcontainer
          push: always
